In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import PolynomialFeatures
import warnings
warnings.filterwarnings("ignore")
np.random.seed(42)

In [15]:
df=pd.read_csv("C:/Users/Kannan/Desktop/hema/loan_data.csv")
y=df.pop("not.fully.paid")

In [16]:
df.head()

,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec
0,1,debt_consolidation,0.1189,829.10,11.350407,19.48,737,5639.958333,28854,52.1,0,0,0
1,1,credit_card,0.1071,228.22,11.082143,14.29,707,2760.000000,33623,76.7,0,0,0
2,1,debt_consolidation,0.1357,366.86,10.373491,11.63,682,4710.000000,3511,25.6,1,0,0
3,1,debt_consolidation,0.1008,162.34,11.350407,8.10,712,2699.958333,33667,73.2,1,0,0
4,1,credit_card,0.1426,102.92,11.299732,14.97,667,4066.000000,4740,39.5,0,1,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9578 entries, 0 to 9577
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   purpose            9578 non-null   object
 1   int.rate           9578 non-null   float64
 2   installment        9578 non-null   float64
 3   log.annual.inc     9578 non-null   float64
 4   dti                9578 non-null   float64
 5   fico               9578 non-null   int64
 6   days.with.cr.line  9578 non-null   float64
 7   revol.bal          9578 non-null   int64
 8   revol.util         9578 non-null   float64
 9   inq.last.6mths     9578 non-null   int64
 10  delinq.2yrs        9578 non-null   int64
 11  pub.rec            9578 non-null   int64
 12  not.fully.paid     9578 non-null   int64
dtypes: float64(6), int64(6), object(1)
memory usage: 972.9+ KB

In [5]:
dummies = pd.get_dummies(df.purpose)
dummies

,all_other,credit_card,debt_consolidation,educational,home_improvement,major_purchase,small_business
0,0,0,1,0,0,0,0
1,0,1,0,0,0,0,0
2,0,0,1,0,0,0,0
3,0,0,1,0,0,0,0
4,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...
9573,1,0,0,0,0,0,0
9574,1,0,0,0,0,0,0
9575,0,0,1,0,0,0,0
9576,0,0,0,0,1,0,0
9577,0,0,1,0,0,0,0

In [6]:
merged = pd.concat([df,dummies],axis='columns')
merged

,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,all_other,credit_card,debt_consolidation,educational,home_improvement,major_purchase,small_business
0,debt_consolidation,0.1189,829.10,11.350407,19.48,737,5639.958333,28854,52.1,0,0,0,0,0,0,1,0,0,0,0
1,credit_card,0.1071,228.22,11.082143,14.29,707,2760.000000,33623,76.7,0,0,0,0,0,1,0,0,0,0,0
2,debt_consolidation,0.1357,366.86,10.373491,11.63,682,4710.000000,3511,25.6,1,0,0,0,0,0,1,0,0,0,0
3,debt_consolidation,0.1008,162.34,11.350407,8.10,712,2699.958333,33667,73.2,1,0,0,0,0,0,1,0,0,0,0
4,credit_card,0.1426,102.92,11.299732,14.97,667,4066.000000,4740,39.5,0,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9573,all_other,0.1461,344.76,12.180755,10.39,672,10474.000000,215372,82.1,2,0,0,1,1,0,0,0,0,0,0
9574,all_other,0.1253,257.70,11.141862,0.21,722,4380.000000,184,1.1,5,0,0,1,1,0,0,0,0,0,0
9575,debt_consolidation,0.1071,97.81,10.596635,13.09,687,3450.041667,10036,82.9,8,0,0,1,0,0,1,0,0,0,0
9576,home_improvement,0.1600,351.58,10.819778,19.18,692,1800.000000,0,3.2,5,0,0,1,0,0,0,0,1,0,0
9577,debt_consolidation,0.1392,853.43,11.264464,16.28,732,4740.000000,37879,57.0,6,0,0,1,0,0,1,0,0,0,0

In [10]:
df = merged.drop(['purpose'], axis='columns')
df

,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid,all_other,credit_card,debt_consolidation,educational,home_improvement,major_purchase,small_business
0,0.1189,829.10,11.350407,19.48,737,5639.958333,28854,52.1,0,0,0,0,0,0,1,0,0,0,0
1,0.1071,228.22,11.082143,14.29,707,2760.000000,33623,76.7,0,0,0,0,0,1,0,0,0,0,0
2,0.1357,366.86,10.373491,11.63,682,4710.000000,3511,25.6,1,0,0,0,0,0,1,0,0,0,0
3,0.1008,162.34,11.350407,8.10,712,2699.958333,33667,73.2,1,0,0,0,0,0,1,0,0,0,0
4,0.1426,102.92,11.299732,14.97,667,4066.000000,4740,39.5,0,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9573,0.1461,344.76,12.180755,10.39,672,10474.000000,215372,82.1,2,0,0,1,1,0,0,0,0,0,0
9574,0.1253,257.70,11.141862,0.21,722,4380.000000,184,1.1,5,0,0,1,1,0,0,0,0,0,0
9575,0.1071,97.81,10.596635,13.09,687,3450.041667,10036,82.9,8,0,0,1,0,0,1,0,0,0,0
9576,0.1600,351.58,10.819778,19.18,692,1800.000000,0,3.2,5,0,0,1,0,0,0,0,1,0,0
9577,0.1392,853.43,11.264464,16.28,732,4740.000000,37879,57.0,6,0,0,1,0,0,1,0,0,0,0

In [11]:
train,test,y_train,y_test=train_test_split(df,y,test_size=0.2,random_state=101)

In [12]:
lr=LogisticRegression()
lr.fit(train,y_train)
y_pred=lr.predict(test)
print("Accuracy score",accuracy_score(y_test,y_pred))

Accuracy score 0.8721294363256785

In [54]:


def fit_predict(train, test, y_train, y_test, scaler, max_depth, 
                criterion = 'entropy', max_features = 1, min_samples_split = 4):
    train_scaled = scaler.fit_transform(train)
    test_scaled = scaler.transform(test)        
    dt = DecisionTreeClassifier(criterion = criterion, max_depth=max_depth, 
                                random_state=42, max_features=max_features,
                               min_samples_split=min_samples_split)
    dt.fit(train_scaled, y_train)
    y_pred = dt.predict(test_scaled)
    print(accuracy_score(y_test, y_pred))

In [55]:
dt=DecisionTreeClassifier()
dt.fit(train,y_train)
y_pred=dt.predict(test)
print(accuracy_score(y_test,y_pred))

0.9921711899791231

In [37]:
max_depth = []
for i in range(1, 20):
    print("Accuracy using Max Depth =", i, end = ': ')
    fit_predict(train, test, y_train, y_test, StandardScaler(), i)

Accuracy using Max Depth = 1: 0.808455114822547
Accuracy using Max Depth = 2: 0.808455114822547
Accuracy using Max Depth = 3: 0.8079331941544885
Accuracy using Max Depth = 4: 0.8152400835073069
Accuracy using Max Depth = 5: 0.8220250521920668
Accuracy using Max Depth = 6: 0.8376826722338204
Accuracy using Max Depth = 7: 0.8778705636743215
Accuracy using Max Depth = 8: 0.8408141962421712
Accuracy using Max Depth = 9: 0.8303757828810021
Accuracy using Max Depth = 10: 0.9018789144050104
Accuracy using Max Depth = 11: 0.8987473903966597
Accuracy using Max Depth = 12: 0.9044885177453027
Accuracy using Max Depth = 13: 0.8820459290187892
Accuracy using Max Depth = 14: 0.8810020876826722
Accuracy using Max Depth = 15: 0.8632567849686847
Accuracy using Max Depth = 16: 0.9164926931106472
Accuracy using Max Depth = 17: 0.8997912317327766
Accuracy using Max Depth = 18: 0.8815240083507306
Accuracy using Max Depth = 19: 0.901356993736952

In [39]:
for i in np.arange(0.1, 1.0, 0.1):
    print("Accuracy using Max Feature =", i, end = ': ')
    fit_predict(train, test, y_train, y_test, StandardScaler(), max_depth = 5, max_features= i)

Accuracy using Max Feature = 0.1: 0.8220250521920668
Accuracy using Max Feature = 0.2: 0.9008350730688935
Accuracy using Max Feature = 0.30000000000000004: 0.964509394572025
Accuracy using Max Feature = 0.4: 0.9775574112734864
Accuracy using Max Feature = 0.5: 0.975991649269311
Accuracy using Max Feature = 0.6: 0.9780793319415448
Accuracy using Max Feature = 0.7000000000000001: 0.8919624217118998
Accuracy using Max Feature = 0.8: 0.9791231732776617
Accuracy using Max Feature = 0.9: 0.9838204592901879

In [41]:
for i in range(2, 10):
    print("Accuracy using Min Sample Split =", i, end = ': ')
    fit_predict(train, test, y_train, y_test, StandardScaler(), max_depth = 16, min_samples_split= i)

Accuracy using Min Sample Split = 2: 0.901356993736952
Accuracy using Min Sample Split = 3: 0.8778705636743215
Accuracy using Min Sample Split = 4: 0.9164926931106472
Accuracy using Min Sample Split = 5: 0.8669102296450939
Accuracy using Min Sample Split = 6: 0.8877870563674322
Accuracy using Min Sample Split = 7: 0.9237995824634656
Accuracy using Min Sample Split = 8: 0.8919624217118998
Accuracy using Min Sample Split = 9: 0.8956158663883089

In [42]:
for i in ['gini', 'entropy']:
    print("Accuracy using Criterion =", i, end = ': ')
    fit_predict(train, test, y_train, y_test, StandardScaler(), max_depth = 16, 
                criterion = i)

Accuracy using Criterion = gini: 0.8804801670146137
Accuracy using Criterion = entropy: 0.9164926931106472

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
rf=RandomForestClassifier(criterion='gini')

In [22]:
rf.fit(train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [23]:
pred_rf = rf.predict(test)

In [24]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,pred_rf))

0.988517745302714

In [25]:
from sklearn.model_selection import GridSearchCV

In [26]:
params={'n_estimators':[200,500,700],'max_depth':[10,15,18,20],
       'min_samples_leaf':[3,5,7]}

In [27]:
gs=GridSearchCV(rf,params,cv=3,verbose=3)

In [28]:
gs.fit(train,y_train)

Fitting 3 folds for each of 36 candidates, totalling 108 fits
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.983, total=   1.9s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.8s remaining:    0.0s

[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.989, total=   1.8s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    3.5s remaining:    0.0s

[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.988, total=   1.7s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=0.982, total=   4.4s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=0.989, total=   4.3s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=0.987, total=   4.1s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=700, score=0.982, total=   5.7s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=700, score=0.989, total=   6.2s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=700, score=0.987, total=   6.1s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=200, score=0.982, total=   1.7s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=200, score=0.989, total=   1.6s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=200, score=0.986, total=   1.6s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=500, score=0.983, total=   4.3s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=500, score=0.989, total=   4.0s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=500, score=0.987, total=   4.0s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=700, score=0.982, total=   5.6s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=700, score=0.989, total=   6.0s
[CV] max_depth=10, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=5, n_estimators=700, score=0.986, total=   5.6s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=200, score=0.982, total=   1.6s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=200, score=0.989, total=   1.6s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=200, score=0.986, total=   1.6s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=500, score=0.982, total=   4.0s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=500, score=0.989, total=   4.1s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=500, score=0.986, total=   4.2s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=700, score=0.982, total=   5.7s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=700, score=0.989, total=   5.7s
[CV] max_depth=10, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=7, n_estimators=700, score=0.986, total=   5.6s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=200, score=0.983, total=   1.9s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=200, score=0.989, total=   1.9s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=200, score=0.988, total=   2.0s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=500, score=0.983, total=   4.7s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=500, score=0.989, total=   5.0s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=500, score=0.988, total=   5.0s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.982, total=   6.8s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.990, total=   7.0s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.988, total=   6.9s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=200, score=0.983, total=   1.9s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=200, score=0.988, total=   2.1s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=200, score=0.986, total=   2.0s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=500, score=0.983, total=   4.7s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=500, score=0.989, total=   4.6s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=500, score=0.986, total=   4.8s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=700, score=0.983, total=   7.1s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=700, score=0.989, total=   6.5s
[CV] max_depth=15, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=5, n_estimators=700, score=0.987, total=   7.0s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=200, score=0.982, total=   1.9s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=200, score=0.989, total=   1.8s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=200, score=0.986, total=   1.8s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=500, score=0.982, total=   4.6s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=500, score=0.989, total=   4.5s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=500, score=0.986, total=   4.6s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=700, score=0.982, total=   6.8s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=700, score=0.988, total=   6.4s
[CV] max_depth=15, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=7, n_estimators=700, score=0.986, total=   6.8s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=200, score=0.983, total=   1.9s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=200 ..............

[CV]  max_depth=18, min_samples_leaf=3, n_estimators=200, score=0.990, total=   2.0s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=200, score=0.988, total=   2.0s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=500, score=0.982, total=   4.8s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=500, score=0.990, total=   5.0s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=500, score=0.988, total=   4.8s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=700, score=0.983, total=   6.7s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=700, score=0.989, total=   6.9s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=700, score=0.988, total=   6.8s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=200, score=0.982, total=   1.9s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=200, score=0.988, total=   1.9s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=200, score=0.987, total=   1.9s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=500, score=0.983, total=   4.8s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=500, score=0.989, total=   5.0s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=500, score=0.987, total=   4.8s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=700, score=0.983, total=   6.6s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=700, score=0.988, total=   6.7s
[CV] max_depth=18, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=5, n_estimators=700, score=0.986, total=   6.7s
[CV] max_depth=18, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=7, n_estimators=200, score=0.982, total=   1.9s
[CV] max_depth=18, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=7, n_estimators=200, score=0.988, total=   1.9s
[CV] max_depth=18, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=7, n_estimators=200, score=0.986, total=   2.0s
[CV] max_depth=18, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=7, n_estimators=500, score=0.982, total=   4.9s
[CV] max_depth=18, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=7, n_estimators=500, score=0.988, total=   4.7s
[CV] max_depth=18, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=7, n_estimators=500, score=0.987, total=   4.7s
[CV] max_depth=18, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=7, n_estimators=700, score=0.983, total=   7.0s
[CV] max_depth=18, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=7, n_estimators=700, score=0.988, total=   7.0s
[CV] max_depth=18, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=7, n_estimators=700, score=0.986, total=   7.6s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=200, score=0.984, total=   2.7s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=200, score=0.989, total=   2.7s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=200, score=0.988, total=   3.0s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=500, score=0.983, total=   6.2s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=500, score=0.989, total=   5.1s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=500, score=0.987, total=   5.3s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=700, score=0.983, total=   7.8s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=700, score=0.990, total=   7.6s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=700, score=0.988, total=   7.4s
[CV] max_depth=20, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=5, n_estimators=200, score=0.983, total=   2.0s
[CV] max_depth=20, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=5, n_estimators=200, score=0.989, total=   2.1s
[CV] max_depth=20, min_samples_leaf=5, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=5, n_estimators=200, score=0.986, total=   2.1s
[CV] max_depth=20, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=5, n_estimators=500, score=0.983, total=   5.0s
[CV] max_depth=20, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=5, n_estimators=500, score=0.989, total=   4.9s
[CV] max_depth=20, min_samples_leaf=5, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=5, n_estimators=500, score=0.986, total=   4.9s
[CV] max_depth=20, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=5, n_estimators=700, score=0.983, total=   7.4s
[CV] max_depth=20, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=5, n_estimators=700, score=0.989, total=   7.2s
[CV] max_depth=20, min_samples_leaf=5, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=5, n_estimators=700, score=0.986, total=   6.9s
[CV] max_depth=20, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=7, n_estimators=200, score=0.982, total=   1.9s
[CV] max_depth=20, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=7, n_estimators=200, score=0.989, total=   2.1s
[CV] max_depth=20, min_samples_leaf=7, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=7, n_estimators=200, score=0.986, total=   2.0s
[CV] max_depth=20, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=7, n_estimators=500, score=0.983, total=   4.9s
[CV] max_depth=20, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=7, n_estimators=500, score=0.988, total=   4.8s
[CV] max_depth=20, min_samples_leaf=7, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=7, n_estimators=500, score=0.987, total=   4.9s
[CV] max_depth=20, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=7, n_estimators=700, score=0.982, total=   6.9s
[CV] max_depth=20, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=7, n_estimators=700, score=0.988, total=   6.7s
[CV] max_depth=20, min_samples_leaf=7, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=7, n_estimators=700, score=0.987, total=   6.7s

[Parallel(n_jobs=1)]: Done 108 out of 108 | elapsed:  8.0min finished

GridSearchCV(cv=3, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'max_depth': [10, 15, 18, 20],
                         'min_samples_leaf': [3, 5, 7],
                         'n_estimators': [200, 500, 700]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [29]:
gs.best_params_

{'max_depth': 20, 'min_samples_leaf': 3, 'n_estimators': 200}

In [30]:
gs.best_estimator_

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=20, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [43]:
rf1=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=16, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [44]:
rf1.fit(train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=16, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [45]:
rf1.oob_score_

0.9876011485251892

In [46]:
pred_rf1=rf1.predict(test)

In [47]:
print(accuracy_score(y_test,pred_rf1))

0.9879958246346555

In [48]:
rf1.feature_importances_

array([3.75363480e-02, 1.29384830e-02, 1.49128668e-02, 5.33302190e-02,
       2.35214099e-01, 1.15617510e-01, 6.85886324e-02, 2.16287144e-02,
       4.27516610e-01, 1.91779576e-03, 6.03654388e-04, 5.38133166e-03,
       1.02062433e-03, 6.87675384e-04, 9.93751265e-04, 1.40055480e-04,
       8.57101510e-04, 1.23414046e-04, 9.91113983e-04])

In [50]:
sorted(list(zip(rf1.feature_importances_,train.columns)),reverse=True)

[(0.42751660993264057, 'inq.last.6mths'),
 (0.23521409916351765, 'fico'),
 (0.11561750954202943, 'days.with.cr.line'),
 (0.06858863243979371, 'revol.bal'),
 (0.053330218953298855, 'dti'),
 (0.037536347955910244, 'int.rate'),
 (0.02162871436429867, 'revol.util'),
 (0.014912866835977817, 'log.annual.inc'),
 (0.012938483012932343, 'installment'),
 (0.005381331661554021, 'not.fully.paid'),
 (0.0019177957556618349, 'delinq.2yrs'),
 (0.0010206243264624427, 'all_other'),
 (0.0009937512651476668, 'debt_consolidation'),
 (0.0009911139832930727, 'small_business'),
 (0.0008571015098143908, 'home_improvement'),
 (0.0006876753839847046, 'credit_card'),
 (0.000603654387657254, 'pub.rec'),
 (0.00014005547956383636, 'educational'),
 (0.00012341404646142013, 'major_purchase')]